version: "3.7"

services:
  app:
    image: ghcr.io/yanislav-igonin/ip-crawler/ip-crawler:latest
    networks:
      - web
    environment: 
      DATABASE_URL: ${DATABASE_URL}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"

networks:
  web:
    driver: overlay
    external: true
